apiVersion: v1
kind: ConfigMap
metadata:  
  name: worker-test2-configmap
  namespace: default
data:
  VariableTest: Variavel_Worker2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-test2
  namespace: default
spec:
  selector:
    matchLabels:
      app: worker-test2
  template:
    metadata:
      labels:
        app: worker-test2
    spec:
      containers:
        - name: worker-test2
          image: acslook/workertest:latest
          envFrom:
            - configMapRef:
                name: worker-test2-configmap