apiVersion: v1
kind: ConfigMap
metadata:  
  name: worker-test1-configmap
  namespace: default
data:
  VariableTest: Variavel_Worker1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-test1
  namespace: default
spec:
  selector:
    matchLabels:
      app: worker-test1
  template:
    metadata:
      labels:
        app: worker-test1
    spec:
      containers:
        - name: worker-test1
          image: acslook/workertest:latest
          envFrom:
            - configMapRef:
                name: worker-test1-configmap